# Generated by Django 4.1.7 on 2023-04-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement_officer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPO',
            fields=[
                ('admin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='placement_officer.admin')),
            ],
            bases=('placement_officer.admin',),
        ),
    ]
