# Generated by Django 4.1.7 on 2023-04-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcastudentdetails',
            options={'verbose_name_plural': 'Student Details'},
        ),
    ]
