# Generated by Django 4.1.7 on 2023-03-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='explanation',
            field=models.TextField(default=''),
        ),
    ]
