# Generated by Django 4.1.7 on 2023-03-21 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aikenquizformat',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aikenquizformat',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
