# Generated by Django 4.1.7 on 2023-03-29 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aikenfile',
            options={'verbose_name_plural': 'Aiken Quiz'},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quiz'},
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Quiz Name'),
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='time',
            field=models.CharField(default='10', max_length=10, verbose_name='Time(Minutes)'),
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='uploaded_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Upload Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aikenfile',
            name='file',
            field=models.FileField(default='', upload_to='files', verbose_name='File'),
        ),
    ]
