# Generated by Django 4.1.7 on 2023-03-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_quesmodel_explanation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quesmodel',
            options={'verbose_name_plural': 'Quick Test'},
        ),
    ]
