# Generated by Django 4.1.7 on 2023-03-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_aikenquizformat_end_date_aikenquizformat_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikenquizformat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Quiz Name'),
        ),
    ]
