# Generated by Django 4.1.7 on 2023-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_alter_mcastudentdetails_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('primary_number', models.CharField(max_length=10, unique=True)),
                ('secondary_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Admin Table',
            },
        ),
        migrations.DeleteModel(
            name='Tpo',
        ),
    ]
