# Generated by Django 4.1.7 on 2023-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_aiken_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcastudentdetails',
            old_name='admino',
            new_name='user',
        ),
        migrations.AddField(
            model_name='mcastudentdetails',
            name='universityReg',
            field=models.CharField(default='AJC21MCA-2095', max_length=13, verbose_name='KTU register number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='DoB',
            field=models.DateField(max_length=10, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='activeArrears',
            field=models.CharField(max_length=2, verbose_name='Active Arrears (Count)'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='alternativeNo',
            field=models.CharField(max_length=15, verbose_name='Alternative Mobile'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='branch',
            field=models.CharField(choices=[('mca', 'MCA'), ('intmca', 'INT MCA')], max_length=50, verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='collegeMail',
            field=models.CharField(max_length=200, verbose_name='College Mail'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='collegeNameUg',
            field=models.CharField(max_length=50, verbose_name='UG College Name'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='entranceRank',
            field=models.CharField(max_length=6, verbose_name='Entrance Rank'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='examsNotAttended',
            field=models.CharField(max_length=2, verbose_name='Exam not Attended (Count)'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='fatherName',
            field=models.CharField(max_length=50, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='fatherNo',
            field=models.CharField(max_length=15, verbose_name="Father's Mobile"),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='fullAddress',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='historyOfArrears',
            field=models.CharField(max_length=2, verbose_name='Arrears History(Active + Cleared)'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='hseBoard',
            field=models.CharField(max_length=30, verbose_name='HSE/12 Board'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='hsePer',
            field=models.CharField(max_length=5, verbose_name='HSE/12 Percent'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='hseYoP',
            field=models.CharField(max_length=4, verbose_name='HSE/12 Year of Pass'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='linkedIn',
            field=models.URLField(max_length=500, verbose_name='LinkedIn Profile URL'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='mcaAggregateCgpa',
            field=models.CharField(max_length=4, verbose_name='PG CGPA'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='mobileNoIndian',
            field=models.CharField(max_length=10, verbose_name='Primary Mobile'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='motherName',
            field=models.CharField(max_length=30, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='motherNo',
            field=models.CharField(max_length=15, verbose_name="Mother's Mobile"),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='nameOfUG',
            field=models.CharField(max_length=10, verbose_name='UG Programme'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='nationality',
            field=models.CharField(max_length=15, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='pgUniversity',
            field=models.CharField(default='APJ KTU', max_length=50, verbose_name='PG University'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='pincode',
            field=models.CharField(max_length=6, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='planAfterGraduate',
            field=models.CharField(max_length=15, verbose_name='Future Plan'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='projectGithub',
            field=models.URLField(max_length=500, verbose_name='GitHub Profile URL'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='sslcBoard',
            field=models.CharField(max_length=35, verbose_name='SSLC/10 Board'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='sslcPer',
            field=models.FloatField(max_length=5, verbose_name='SSLC/10 Percent'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='sslcYoP',
            field=models.CharField(max_length=4, verbose_name='SSLC/10 Year of Pass'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='ugCgpa',
            field=models.CharField(max_length=5, verbose_name='UG CGPA'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='ugPer',
            field=models.CharField(max_length=5, verbose_name='UG Percent'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='ugUniversity',
            field=models.CharField(max_length=50, verbose_name='UG University'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='ugYoP',
            field=models.CharField(max_length=4, verbose_name='UG Year of Pass'),
        ),
    ]
