# Generated by Django 4.1.7 on 2023-03-27 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_alter_aikenquizformat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='quiz_taken_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date & Time'),
            preserve_default=False,
        ),
    ]
