# Generated by Django 4.1.7 on 2023-02-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_payment_status_alter_payment_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applydrive',
            options={'verbose_name_plural': 'Students Applied'},
        ),
        migrations.AlterModelOptions(
            name='drives',
            options={'verbose_name_plural': 'Company Details'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
