# Generated by Django 4.1.7 on 2023-03-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_alter_quesmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aikenfile',
            options={'verbose_name_plural': 'Aptitude Quiz File'},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Aptitude Quiz Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Aptitude Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Aptitude Quiz Title'},
        ),
    ]
