# Generated by Django 4.1.7 on 2023-04-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_admin_delete_tpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
