# Generated by Django 4.1.7 on 2023-02-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_alter_applydrive_options_alter_drives_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payment Table'},
        ),
    ]
