# Generated by Django 4.1.7 on 2023-03-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_quizresult_quiz_taken_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('not paid', 'not paid')], default='Not Paid', max_length=25),
        ),
    ]
