# Generated by Django 4.1.7 on 2023-03-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_alter_aikenfile_options_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aikenfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
    ]
