# Generated by Django 4.1.7 on 2023-04-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='company image', verbose_name='Company Image')),
            ],
            options={
                'verbose_name_plural': "Company's Images",
            },
        ),
        migrations.AlterModelOptions(
            name='applydrive',
            options={'verbose_name_plural': 'Drives Applied'},
        ),
        migrations.AlterModelOptions(
            name='drives',
            options={'verbose_name_plural': 'Drive Details'},
        ),
        migrations.RemoveField(
            model_name='applydrive',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='applydrive',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='drives',
            name='drive_id',
        ),
        migrations.AddField(
            model_name='applydrive',
            name='applied_on',
            field=models.DateField(auto_now_add=True, default='2023-04-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applydrive',
            name='drive_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campus.drives', verbose_name='Drive Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applydrive',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Applied'),
        ),
        migrations.AddField(
            model_name='drives',
            name='backlog',
            field=models.IntegerField(default=0, verbose_name='Backlog Count'),
        ),
        migrations.AddField(
            model_name='drives',
            name='cgpa',
            field=models.FloatField(default='6', verbose_name='Required CGPA'),
        ),
        migrations.AddField(
            model_name='drives',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drives',
            name='pg_percentage',
            field=models.IntegerField(default='60', verbose_name='PG Percent'),
        ),
        migrations.AddField(
            model_name='drives',
            name='ug_percentage',
            field=models.IntegerField(default='60', verbose_name='UG Percent'),
        ),
        migrations.AlterField(
            model_name='drives',
            name='company_name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='drives',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Job Role'),
        ),
        migrations.AlterField(
            model_name='drives',
            name='last_date',
            field=models.DateField(default='', verbose_name='Last Date'),
        ),
        migrations.AlterField(
            model_name='drives',
            name='salary_package',
            field=models.FloatField(default='', max_length=10, verbose_name='CTC(LPA)'),
        ),
        migrations.AlterField(
            model_name='drives',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Accept Response'),
        ),
    ]
