# Generated by Django 4.1.7 on 2023-04-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_company_image_alter_applydrive_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcastudentdetails',
            name='plan_after_graduate',
            field=models.CharField(choices=[('Job', 'Job'), ('start-up', 'start-up'), ('Higher Studies', 'Higher Studies')], default='Job', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='hseBoard',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('HSE', 'HSE'), ('ISC', 'ISC'), ('VHSE', 'VHSE'), ('IHRD', 'IHRD')], max_length=30, verbose_name='HSE/12 Board'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='hseYoP',
            field=models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='HSE/12 Year of Pass'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='nameOfUG',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('B.Sc CS', 'B.Sc CS'), ('B.Sc Electronics', 'B.Sc Electronics'), ('B.Com', 'B.Com')], max_length=50, verbose_name='UG Programme'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='pgUniversity',
            field=models.CharField(choices=[('APJ KTU', 'APJ KTU')], max_length=50, verbose_name='PG University'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='sslcBoard',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('State Board of Kerala', 'State Board of Kerala'), ('State Board of Andhra Pradesh', 'State Board of Andhra Pradesh'), ('State Board of Tamil Nadu', 'State Board of Tamil Nadu'), ('State Board of Karnataka', 'State Board of Karnataka')], max_length=35, verbose_name='SSLC/10 Board'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='sslcYoP',
            field=models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], max_length=4, verbose_name='SSLC/10 Year of Pass'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='ugUniversity',
            field=models.CharField(choices=[('APJ KTU', 'APJ KTU'), ('Mahatma Gandhi University', 'Mahatma Gandhi University'), ('Kannur University', 'Kannur University'), ('CUSAT', 'CUSAT'), ('University of Kerala', 'University of Kerala'), ('National Institute of Technology', 'National Institute of Technology')], max_length=50, verbose_name='UG University'),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='ugYoP',
            field=models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='UG Year of Pass'),
        ),
    ]
