# Generated by Django 4.1.7 on 2023-03-28 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_alter_aikenfile_options_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aikenfile',
            options={'verbose_name_plural': 'Aiken Aptitude Quiz'},
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='end_date',
            field=models.DateField(default='', verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Quiz Name'),
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='start_date',
            field=models.DateField(default='', verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='time',
            field=models.IntegerField(default=15, verbose_name='Time(Minutes)'),
        ),
        migrations.AddField(
            model_name='aikenfile',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='uploaded on'),
            preserve_default=False,
        ),
    ]
