# Generated by Django 4.1.7 on 2023-03-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_quizresult_alter_quesmodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
