# Generated by Django 4.1.7 on 2023-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_alter_drives_pg_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcastudentdetails',
            name='mcaPer',
            field=models.CharField(default=70, max_length=5, verbose_name='PG Percent'),
            preserve_default=False,
        ),
    ]
