# Generated by Django 4.1.7 on 2023-04-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_mcastudentdetails_mcaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('American', 'American'), ('British', 'British'), ('Canadian', 'Canadian'), ('Australian', 'Australian'), ('Bangladeshi', 'Bangladeshi')], max_length=15, verbose_name='Nationality'),
        ),
    ]
