# Generated by Django 4.1.7 on 2023-03-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_delete_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
    ]
