# Generated by Django 4.1.7 on 2023-03-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_quizresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'verbose_name_plural': 'Quiz - Result'},
        ),
        migrations.AddField(
            model_name='quizresult',
            name='correct',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='percent',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='score',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='time',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='wrong',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='email',
            field=models.EmailField(default=0, max_length=70),
        ),
    ]
