# Generated by Django 4.1.7 on 2023-03-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_alter_quizresult_options_quizresult_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='total',
            field=models.CharField(default=0, max_length=3, verbose_name='total questions'),
        ),
    ]
