# Generated by Django 4.1.7 on 2023-04-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_alter_applydrive_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applydrive',
            options={'verbose_name_plural': 'Students Applied Drives'},
        ),
        migrations.RenameField(
            model_name='applydrive',
            old_name='email',
            new_name='user',
        ),
    ]
