# Generated by Django 4.1.7 on 2023-03-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_alter_quizresult_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quesmodel',
            options={},
        ),
    ]
