# Generated by Django 4.1.7 on 2023-04-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcastudentdetails',
            name='district',
            field=models.CharField(choices=[('Trivandrum', 'Trivandrum'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Eranakulam', 'Eranakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Kannur', 'Kannur'), ('Malappuram', 'Malappuram'), ('Wayanad', 'Wayanad'), ('kozhikkodu', 'Kozhikkodu'), ('Kasargod', 'Kasargod')], default='Pathanamthitta', max_length=50, verbose_name='District'),
            preserve_default=False,
        ),
    ]
