# Generated by Django 4.1.7 on 2023-03-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0013_aikenquizformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikenquizformat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
