# Generated by Django 4.1.7 on 2023-04-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_alter_mcastudentdetails_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='district',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Eranakulam', 'Eranakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Kannur', 'Kannur'), ('Malappuram', 'Malappuram'), ('Wayanad', 'Wayanad'), ('Kozhikkodu', 'Kozhikkodu'), ('Kasargod', 'Kasargod')], max_length=50, verbose_name='District'),
        ),
    ]
