# Generated by Django 4.1.7 on 2023-03-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_alter_aikenquizformat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aikenquizformat',
            name='file_path',
        ),
        migrations.AddField(
            model_name='aikenquizformat',
            name='file',
            field=models.FileField(default='', upload_to='files', verbose_name='File'),
        ),
    ]
