# Generated by Django 4.1.7 on 2023-04-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0015_alter_mcastudentdetails_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcastudentdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile picture', verbose_name='Upload Picture'),
        ),
    ]
