# Generated by Django 4.1.7 on 2023-03-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0017_remove_question_quiz_aikenquizformat_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikenquizformat',
            name='time',
            field=models.CharField(default='10', max_length=10, verbose_name='Time(Minutes)'),
        ),
    ]
