# Generated by Django 4.1.7 on 2023-05-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0017_drives_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
