# Generated by Django 4.1.7 on 2023-05-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0018_tpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
