# Generated by Django 4.1.7 on 2023-05-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0019_alter_tpo_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='pi_3Mk7H1SIBKZt2GrF1SDZTxqe', max_length=255),
            preserve_default=False,
        ),
    ]
