# Generated by Django 4.1.7 on 2023-05-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0022_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('RMCA-A', 'RMCA-A'), ('RMCA-B', 'RMCA-B'), ('INT-MCA', 'INT-MCA')], max_length=30, unique=True, verbose_name='Class Name')),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.AddField(
            model_name='mcastudentdetails',
            name='class_name',
            field=models.CharField(choices=[('RMCA-A', 'RMCA-A'), ('RMCA-B', 'RMCA-B'), ('INT-MCA', 'INT-MCA')], default='RMCA-B', max_length=20, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='btechstudentdetails',
            name='admino',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.studentreg'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Mail ID')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campus.department', verbose_name='Department')),
            ],
            options={
                'verbose_name_plural': 'Table Teacher',
            },
        ),
    ]
